CREATE TABLE IF NOT EXISTS PRICES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID INT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    CURR VARCHAR(3) NOT NULL,
    CONSTRAINT UK_BRAND_PRODUCT UNIQUE (BRAND_ID, PRODUCT_ID, START_DATE, END_DATE)
);

CREATE INDEX IF NOT EXISTS IDX_PRODUCT_BRAND ON PRICES (PRODUCT_ID, BRAND_ID);
CREATE INDEX IF NOT EXISTS IDX_START_DATE ON PRICES (START_DATE);
CREATE INDEX IF NOT EXISTS IDX_END_DATE ON PRICES (END_DATE);